baseurl = "http://spinaldevelopment.com/"
languageCode = "en-us"
title = "Spinal Coding"
theme = "detox"
PygmentsCodeFences = true
builddrafts = false
canonifyurls = true
enableEmoji = false
editor = "atom"

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Spinal Develoment Coding Blog"
  author = "≈Åukasz Kwoska"
  disqusShortname = "Szaq"
  google_analytics = "UA-79477025-1"
